### ISSUE TITLE
table rss.rss 的对应格式是什么

### ISSUE THREAD

**Issue by GideonSenku** [Maidang1/rss-feishu-robot#7]

**Comment by GideonSenku** [comment]
`insert into rss (title, link, pubDate, content, summary, isoDate) values` 这些列的所需的数据表类型

**Comment by Maidang1** [comment]
@GideonSenku 表的信息是这样的
![image](https://github.com/Maidang1/rss-feishu-robot/assets/50993231/ac41178f-4e4b-4c93-a0a9-fd9915c6115a)
